name: 'Setup Standard Env'
description: 'Sets up a standard environment with caching'
inputs:
  python-version:
    description: 'Python version to set up'
    required: false
    default: '3.11'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Install Common Tools
      shell: bash
      run: |
        pip install --upgrade pip wheel setuptools
        echo "Environment setup complete."
